INSERT INTO menu_item(name, description, category, is_veg, price)
VALUES
	('Palak Paneer', 'Flavourful Paneer in a thick paste made from pure spinach, seasoned with Ginger, Garlic, Garam Masala and other spices', 'Main Course', true, 175),
	('Shahi Paneer', 'Popular dish of Mughlai cuisine prepared using paneer, yogurt, milk, fresh cream and paste of almond, cashew and onion', 'Main Course', true, 165),
	('Paneer Do Pyaza', 'Simple curry made with Cottage Cheese and Onions. Do Pyaza means two onion, meaning two types of onion added to its gravy', 'Main Course', true, 135),
	('Kadai Paneer', 'Paneer and bell peppers cooked in a spicy masala. It gets its unique flavor from freshly ground spices like coriander and red chillies', 'Main Course', true, 165),
	('Paneer Butter Masala', 'Creamy dish of paneer, originating from the indian subcontinent, in which gravy is prepared with butter, tomato, cashew and cream', 'Main Course', true, 175),
	('Chicken Masala', 'Dhaba style preperation of chicken in a curry tempered with whole spices', 'Main Course', false, 205),
	('Chicken Korma', 'Aromatic and flavorful chicken gravy seasoned with roasted spices', 'Main Course', false, 205),
	('Chicken Do Pyaza', 'Thick and mildly spiced gravy packed with tender chicken and onions', 'Main Course', false, 195),
	('Kadai Chicken', 'Wok-cooked chicken in spicy onion and tomato gravy', 'Main Course', false, 205),
	('Chicken Butter Masala', 'Marinated chicken is just sauteed and then added to onion tomato gravy', 'Main Course', false, 230),
	('Tandoori Roti', 'Traditional Indian flatbread cooked in a clay oven', 'Breads', true, 20),
	('Butter Tandoori Roti', 'Traditional Indian flatbread cooked in a clay oven and layered with butter', 'Breads', true, 25),
	('Plain Naan', 'Flatbread made with all purpose flour mixed with herbs', 'Breads', true, 40),
	('Butter Naan', 'Topped with butter, this chewy flatbread is baked in traditional clay oven', 'Breads', true, 20),
	('Aloo Paratha', 'Aloo paratha served with curd and pickle', 'Breads', true, 55),
	('Butter Aloo Paratha', 'Butter Aloo paratha served with curd and pickle', 'Breads', true, 70),
	('Rumali Roti', 'Extra larger and thin flatbread made from wheat flour', 'Breads', true, 20),
	('Butter Rumali Roti', 'Extra larger and thin flatbread made from wheat flour and layered with butter', 'Breads', true, 25),
	('Jeera Rice', 'Give your plain rice a nutty twist with a tempering of fresh cumin', 'Rice', true, 90),
	('Peas Rice (Matar Pulao)', 'A delicious combination of white rice and green peas enriched with spices', 'Rice', true, 105),
	('Veg Pulao', 'Assorted vegetables and rice cooked together and seasoned with fragrant spices', 'Rice', true, 125),
	('Paneer Pulao', 'Tickle your palate with this delicious rice pilaf packed with fresh Paneer pieces and spices', 'Rice', true, 135),
	('Veg Fried Rice', 'Vegetables wok tossed and added with zesty spices and sauces to perfectly cooked rice', 'Fried Rice', true, 130),
	('Egg Fried Rice', 'Wok tossed rice sauteed with seasonal vegetables and egg', 'Fried Rice', false, 140),
	('Chicken Fried Rice', 'Wok tossed rice sauteed with seasonal vegetables and chicken', 'Fried Rice', false, 150),
	('Egg Chicken Fried Rice', 'Wok tossed rice sauteed with seasonal vegetables, egg and chicken', 'Fried Rice', false, 160),
	('Veg Chowmein', 'Wok tossed noodles mixed with seasonal vegetables in a light soya based sauce', 'Noodles', true, 109),
	('Egg Chowmein', 'Perfectly seasoned scrambled eggs cooked with buttery noodles', 'Noodles', false, 120),
	('Chicken Chowmein', 'Wok tossed noodles mixed with chicken and seasonal vegetables in a light soya based sauce', 'Noodles', false, 140),
	('Egg Chicken Chowmein', 'Wok tossed noodles mixed with egg, chicken and seasonal vegetables in a light soya based sauce', 'Noodles', false, 150),
	('Paneer Tikka', 'Indian dish made from chunk of paneer marinated in spices and grilled in a tandoor', 'Starter', true, 165),
	('Paneer Reshmi', 'Made with cottage cheese and cooked in rice, creamy gravy with various spices', 'Starter', true, 170),
	('Chicken Tikka', 'Tender chicken breast strips simmered in a bright indian curry made with tomatoes, ginger and indian spices', 'Starter', false, 165),
	('Chicken Reshmi', 'These spicy and creamy chicken kebabs will melt in your mouth', 'Starter', false, 170);
	